version: '3'

services:
    php:
        build: docker/php
        image: php:8.1-fpm-alpine-tokenizer-dev
        volumes:
            - ./:/tokenizer
        networks:
            - tokenizer-network
    nginx:
        image: nginx:1-alpine
        ports:
            - 80:80
        volumes:
            - ./:/tokenizer
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - tokenizer-network
networks:
    tokenizer-network:
        driver: bridge

